services:
#######################
##### MASTER NODE #####
#######################
    master-nginx:
        container_name: powertube_master_nginx_dev
        build:
            context: "./master-node/nginx/"
        depends_on:
            master-nestjs:
                condition: service_started
        restart: always
        develop:
          watch:
            - path: ./master-node/nginx/nginx.conf 
              target: /etc/nginx/nginx.conf
              action: sync+restart
            - path: ./master-node/nginx/route.conf 
              target: /etc/nginx/conf.d/default.conf
              action: sync+restart
        ports:
          - "80:80"
        attach: false
    master-postgres:
        container_name: powertube_master_postgres_dev
        image: postgres:16.4-alpine
        restart: always
        env_file: .env.dev
        volumes:
            - /var/postgres_data:/var/lib/postgresql/data
        expose:
          - "5432"
        attach: false
    master-nestjs:
        container_name: powertube_master_nestjs_dev
        build: 
            context: './master-node/backend/'
            target: dev
            args:
              APPDIR: "."
        expose:
          - "3001"
        restart: always
        env_file: .env.dev
        depends_on:
            master-postgres:
                condition: service_started
        develop:
          watch:
            - path: './master-node/backend/'
              action: sync
              target: /app
              ignore:
                - node_modules
                - dist
                - .vscode
        volumes:
        - ./shared/:/shared:ro
        


#######################
##### WORKER NODE #####
#######################
    worker-squid:
        container_name: powertube_worker_squid_dev
        build:
          context: "./worker-node/squid/"
          args:
            APPDIR: "."
        restart: always
        
        volumes: 
          - "./worker-node/squid/squid.pem:/etc/squid/ssl_cert/squid.pem:ro"
          - "./worker-node/squid/passwd:/etc/squid/passwd:ro"
        attach: false
    # worker-nestjs:
    #     container_name: powertube_worker_nestjs_dev
    #     build: 
    #         context: './worker-node/backend/'
    #         target: dev
    #         args:
    #           APPDIR: "."
            
    #     restart: always
    #     env_file: .env.dev
    #     depends_on:
    #         postgres:
    #             condition: service_started
    #     develop:
    #       watch:
    #         - path: ./worker-node/backend/
    #           action: sync
    #           target: /app
    #           ignore:
    #             - node_modules
    #             - dist
    #             - .vscode
    #     volumes:
    #     - ./shared/:/shared:ro
    #     

# networks:
#   host_net:
#     driver: host
#   master_net:
#     driver: bridge
